wbc = [
    {"total": 1},
    [
          {"id": "CHNBJ", "iso2Code": "CHNBJ", "name": "BEIJING", "region": {"id": "LCN", "value": "Latin America & Caribbean (all income levels)"}, "adminregion": {"id": "", "value": ""}, "incomeLevel": {"id": "NOC", "value": "High income: nonOECD"}, "lendingType": {"id": "LNX", "value": "Not classified"}, "capitalCity": "Oranjestad", "longitude": "116.28", "latitude": "39.54"},
          {"id": "CHNHN", "iso2Code": "CHNHN", "name": "HENAN", "region": {"id": "LCN", "value": "Latin America & Caribbean (all income levels)"}, "adminregion": {"id": "", "value": ""}, "incomeLevel": {"id": "NOC", "value": "High income: nonOECD"}, "lendingType": {"id": "LNX", "value": "Not classified"}, "capitalCity": "Oranjestad", "longitude": "113.42", "latitude": "34.48"},
          {"id": "CHNHB", "iso2Code": "CHNHB", "name": "HEBEI", "region": {"id": "LCN", "value": "Latin America & Caribbean (all income levels)"}, "adminregion": {"id": "", "value": ""}, "incomeLevel": {"id": "NOC", "value": "High income: nonOECD"}, "lendingType": {"id": "LNX", "value": "Not classified"}, "capitalCity": "Oranjestad", "longitude": "114.28", "latitude": "38.02"},
          {"id": "CHNSC", "iso2Code": "CHNSC", "name": "SICHUAN", "region": {"id": "LCN", "value": "Latin America & Caribbean (all income levels)"}, "adminregion": {"id": "", "value": ""}, "incomeLevel": {"id": "NOC", "value": "High income: nonOECD"}, "lendingType": {"id": "LNX", "value": "Not classified"}, "capitalCity": "Oranjestad", "longitude": "104.05", "latitude": "30.39"},
          {"id": "CHNGD", "iso2Code": "CHNGD", "name": "GUANGDONG", "region": {"id": "LCN", "value": "Latin America & Caribbean (all income levels)"}, "adminregion": {"id": "", "value": ""}, "incomeLevel": {"id": "NOC", "value": "High income: nonOECD"}, "lendingType": {"id": "LNX", "value": "Not classified"}, "capitalCity": "Oranjestad", "longitude": "113.15", "latitude": "23.08"},
          {"id": "CHNYN", "iso2Code": "CHNYN", "name": "YUNNAN", "region": {"id": "LCN", "value": "Latin America & Caribbean (all income levels)"}, "adminregion": {"id": "", "value": ""}, "incomeLevel": {"id": "NOC", "value": "High income: nonOECD"}, "lendingType": {"id": "LNX", "value": "Not classified"}, "capitalCity": "Oranjestad", "longitude": "102.41", "latitude": "25"},
          {"id": "CHNHLJ", "iso2Code": "CHNHLJ", "name": "HEILONGJIANG", "region": {"id": "LCN", "value": "Latin America & Caribbean (all income levels)"}, "adminregion": {"id": "", "value": ""}, "incomeLevel": {"id": "NOC", "value": "High income: nonOECD"}, "lendingType": {"id": "LNX", "value": "Not classified"}, "capitalCity": "Oranjestad", "longitude": "126.41", "latitude": "45.45"},
          {"id": "CHNSD", "iso2Code": "CHNSD", "name": "SHANDONG", "region": {"id": "LCN", "value": "Latin America & Caribbean (all income levels)"}, "adminregion": {"id": "", "value": ""}, "incomeLevel": {"id": "NOC", "value": "High income: nonOECD"}, "lendingType": {"id": "LNX", "value": "Not classified"}, "capitalCity": "Oranjestad", "longitude": "117", "latitude": "36.38"},
          {"id": "CHNGS", "iso2Code": "CHNGS", "name": "GANSU", "region": {"id": "LCN", "value": "Latin America & Caribbean (all income levels)"}, "adminregion": {"id": "", "value": ""}, "incomeLevel": {"id": "NOC", "value": "High income: nonOECD"}, "lendingType": {"id": "LNX", "value": "Not classified"}, "capitalCity": "Oranjestad", "longitude": "103.49", "latitude": "36.03"}
    ]
];